version: '3.4'

services:
  lanterniot:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - lantern-network
networks:
  lantern-network:
    driver: bridge # a user defined bridge is required; the default bridge network doesn't support name resolution